# 博客信息
blog:
  title: geoqiao's Blog
  description: |
    1. 目前是一名金融行业贷后策略分析师；这里是我的个人空间，记录一些想记录的。
    2. 这个网页基于GitHub Pages & GitHub Actions 自动部署。
    3. 主体 main.py 自己完成，前端主题由AI生成。
  url: https://geoqiao.github.io/
  content_dir: "./contents/"
  blog_dir: "blog/"
  rss_atom_path: "atom.xml"
  author:
    name: geoqiao
    email: geoqiao@example.com
  page_size: 10

# GitHub 相关配置
github:
  name: geoqiao # GitHub 用户名
  repo: geoqiao/geoqiao.github.io # GitHub 仓库名称

# Google Search Console
GoogleSearchConsole:
  content: DRggZlykSzc8M9TyaS0BPSRE7Kvw8W9hHt5pZrIMm3Y # Google Search Console ID
  verify: true # 是否验证

theme:
  path: "templates/PaperMint"
